### PR TITLE
Fixes

### LINKED ISSUE #25: FTBFS 1.2.0
```
16:54 a4:../iptraf-ng/iptraf-ng » make CFLAGS=-O3 -j16
    CC src/ipfilter.o
    CC src/fltmgr.o
    CC src/ipfrag.o
    CC src/servname.o
    CC src/timer.o
    CC src/serv.o
    CC src/revname.o
    CC src/pktsize.o
    CC src/landesc.o
    CC src/options.o
    CC src/promisc.o
    CC src/ifaces.o
    CC src/usage.o
    CC src/iptraf.o
    CC src/itrafmon.o
    CC src/wrapper.o
    CC src/parse-options.o
    CC src/packet.o
    CC src/tcptable.o
    CC src/othptab.o
    CC src/ifstats.o
    CC src/detstats.o
    CC src/deskman.o
    CC src/hostmon.o
    CC src/fltedit.o
    CC src/cidr.o
    CC src/counters.o
    CC src/rate.o
    CC src/capture-pkt.o
    CC src/sockaddr.o
    CC src/capt.o
    CC src/capt-recvmsg.o
    CC src/capt-recvmmsg.o
    CC src/capt-mmap-v2.o
    CC src/capt-mmap-v3.o
    CC src/rvnamed.o
src/capt-recvmmsg.c: In function ‘capt_recvmmsg_find_filled_slot’:
src/capt-recvmmsg.c:27:19: error: invalid use of undefined type ‘struct mmsghdr’
   27 |   if (data->msgvec[slot].msg_len != 0)
```

### LINKED ISSUE #26: 1.2.0: packet receive failed
Reproducer:
* inside a systemd-234 nspawn container
* build & start 1.2.0
* select "IP traffic monitor", select `host0`
* Error ensues: `Packet receive failed / Press a key to continue`

git bisect pinpoints to this

```
043b0387fbd11670b8b09fc5bde168345648d32d is the first bad commit
commit 043b0387fbd11670b8b09fc5bde168345648d32d
Author: Vitezslav Samel <vitezslav@samel.cz>
Date:   Sun Dec 29 09:44:40 2019 +0100

    TPACKET_V3: mlock() mmap()ed address space into RAM
    
    Signed-off-by: Vitezslav Samel <vitezslav@samel.cz>

 src/capt-mmap-v3.c | 8 +++++++-
 1 file changed, 7 insertions(+), 1 deletion(-)
```

### PR DESCRIPTION
**Pull request by vsamel**
Fix problems reported by @jengelh:
- Makefile: protect mandatory compile flags
- packet capture: don't reuse socket for multiple receive functions
- TPACKET_V[23]: continue even if mlock() fails

### CODE REVIEW

**Review by pecameron — APPROVED** [review]
/lgtm
